version: "2"
services:  
  server:
    image: nagpur0.1
    ports:
      - "4001:4001"
      - "27017:27017"
    network_mode: "host"
    restart: unless-stopped
    env_file: ServerSettings.env
    privileged: true
